# Generated by Django 5.0.1 on 2024-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0002_rename_comida_categoria_tipocomida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomida',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
