# Generated by Django 5.0.1 on 2024-01-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0004_alter_tipocomida_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocomida',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
