# Generated by Django 5.0.1 on 2024-01-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comida', '0005_alter_tipocomida_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipocomida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoria', to='comida.tipocomida'),
        ),
    ]
